"""Generate MAP.md — the global vault index."""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone

from claw_librarian.config import Config
from claw_librarian.journal.schema import JournalEntry


def build_map(entries: list[JournalEntry], config: Config) -> str:
    """Build MAP.md content from journal entries."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Vault Map",
        f"> Auto-generated by claw-librarian. Last sync: {now}",
        "",
    ]

    if not entries:
        lines.append("## Active Projects")
        lines.append("")
        lines.append("No active projects.")
        lines.append("")
        lines.append("## Agent Status")
        lines.append("")
        lines.append("No agents seen.")
        return "\n".join(lines)

    # Aggregate per-project info
    project_data: dict[str, dict] = defaultdict(lambda: {
        "last_ts": "", "agents": set(), "last_activity": "",
    })
    agent_data: dict[str, dict] = defaultdict(lambda: {
        "last_ts": "", "project": "",
    })

    for entry in entries:
        proj = entry.project or "(cross-project)"
        pd = project_data[proj]
        if entry.timestamp > pd["last_ts"]:
            pd["last_ts"] = entry.timestamp
            pd["last_activity"] = entry.timestamp
        pd["agents"].add(entry.agent)

        ad = agent_data[entry.agent]
        if entry.timestamp > ad["last_ts"]:
            ad["last_ts"] = entry.timestamp
            ad["project"] = proj

    # Active Projects table
    lines.append("## Active Projects")
    lines.append("")
    lines.append("| Project | Last Activity | Active Agents | Link |")
    lines.append("|---------|--------------|---------------|------|")
    for proj, pd in sorted(project_data.items(), key=lambda x: x[1]["last_ts"], reverse=True):
        agents_str = ", ".join(sorted(pd["agents"]))
        ts = _format_time(pd["last_ts"])
        link = f"[[projects/{proj}/context]]" if proj != "(cross-project)" else ""
        lines.append(f"| {proj} | {ts} | {agents_str} | {link} |")
    lines.append("")

    # Recent Events (capped)
    lines.append("## Recent Events (last 24h)")
    lines.append("")
    recent = sorted(entries, key=lambda e: e.timestamp, reverse=True)
    cap = config.recent_events_cap
    for entry in recent[:cap]:
        ts_short = entry.timestamp[11:16] if len(entry.timestamp) > 16 else entry.timestamp
        proj = entry.project or "cross"
        lines.append(f"- **{ts_short}** {entry.agent}/{proj}: {entry.message}")
    lines.append("")

    # Agent Status table
    lines.append("## Agent Status")
    lines.append("")
    lines.append("| Agent | Last Seen | Current Project |")
    lines.append("|-------|-----------|----------------|")
    for agent, ad in sorted(agent_data.items(), key=lambda x: x[1]["last_ts"], reverse=True):
        ts = _format_time(ad["last_ts"])
        lines.append(f"| {agent} | {ts} | {ad['project']} |")
    lines.append("")

    return "\n".join(lines)


def _format_time(iso_ts: str) -> str:
    """Format ISO timestamp as relative or absolute time string."""
    try:
        dt = datetime.fromisoformat(iso_ts.replace("Z", "+00:00"))
        now = datetime.now(timezone.utc)
        delta = now - dt
        if delta.total_seconds() < 3600:
            mins = int(delta.total_seconds() / 60)
            return f"{mins} min ago"
        elif delta.total_seconds() < 86400:
            hours = int(delta.total_seconds() / 3600)
            return f"{hours} hours ago"
        else:
            days = delta.days
            return f"{days} day{'s' if days != 1 else ''} ago"
    except (ValueError, TypeError):
        return iso_ts
